<a href="https://colab.research.google.com/github/NSteckel/Data-in-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

#### Intro to Numpy

- Numpy = Standard library for python- much slower than lower level languages like C/C++
- Specialized library for numberical computations
- Linear Algebra or mathematics
- Array, matrix and mathematical transformations

- ndarray = ~50x faster than lists in Python
- Contiguious in memory
- fixed size
- Written in the C implementation of Pyhton
- Must contain a single data type

In [ ]:
import numpy as np

print(np.__version__)

1.21.6


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Pass any container in Python - list, tuple, set, iterable
# Auto-convert when you pass that argument

# 0D array is a scalar
scalar = np.array(42)

# 1D array is a array
arr = np.array([1, 2, 3])

# 2D array is a matrix/matrices
matrix = np.array([[1, 2, 3], [2, 4, 6]])

# 3d array is a Tensor (like tensorflow)
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [ ]:
print(scalar.ndim, arr.ndim, matrix.ndim, tensor.ndim)

0 1 2 3


In [ ]:
# Indexing into ndarrays
# The only difference between single and multi-dimensional arrays in Numpy is that we can pass the indexes in a list

py_arr = [[1,2], [3,4], [5,6]]
print(py_arr[2][0])

5


#### Numpy Data Types

- In Numpy, we can use python's base data types
- Numpy actually provides additional types for increased control/speed
- (integer, boolean, integer, float, datetime/timedelta, object, string, etc.)
- 

In [ ]:
# Array Shapes
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.shape)

(2, 3)


In [ ]:
# Reshaping Arrays
# We often read arrays in a flat fromat and have to reshape them

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
matrix = array.reshape(4,3)
print(matrix)
print(matrix.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [ ]:
flat_arr = matrix.resh # Figure out flatten / unshape

In [ ]:
print(tensor)
for x in np.nditer(tensor):
  print(x)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
1
2
3
4
5
6


In [ ]:
# joining arrays
# join by axis (in python axis 0 is row, axis 1 is column)

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Look into H, V and D stacks 
# https://www.geeksforgeeks.org/numpy-vstack-in-python/?ref=lbp
# https://pythonguides.com/python-numpy-stack/

In [ ]:
arr = np.array([1,2,3,4,6,5,4])
x = 